from pathlib import Path
import re
p=Path('index.html')
s=p.read_text(encoding='utf-8')
for marker in ['RAHL1K INVENTORY KARAMBIT V25','RAHL1K INVENTORY KARAMBIT V26']:
    s=re.sub(r'\n?<!-- '+re.escape(marker)+r' -->.*?</script>\s*','\n',s,flags=re.S)
addon=r'''
<!-- RAHL1K INVENTORY KARAMBIT V26 -->
<style>
.v26checks{position:absolute;right:8px;top:8px;display:flex;gap:5px;z-index:40}.v26check{width:25px;height:25px;border-radius:6px;border:2px solid #ffffff28;background:#080d12aa;display:flex;align-items:center;justify-content:center;font-weight:900;opacity:.25}.v26check.on{opacity:1}.v26check.ct{color:#8ed5ff;background:#176aa4cc;border-color:#73c8ff}.v26check.t{color:#ffd09a;background:#a65414cc;border-color:#ffad55}
#karambitInventoryCard{display:flex!important;position:relative!important;flex:0 0 190px!important;width:190px!important;min-width:190px!important;height:145px!important;border:2px solid #ffffff2a!important;border-radius:16px!important;background:linear-gradient(145deg,#263744,#121b22)!important;overflow:hidden!important;touch-action:manipulation!important;pointer-events:auto!important}
#karambitInventoryCard .kType{position:absolute;left:10px;top:9px;color:#ffffff77;font-size:9px;font-weight:800}.k26icon{position:absolute;left:50%;top:51%;width:110px;height:86px;transform:translate(-50%,-50%) rotate(-18deg)}.k26blade{position:absolute;left:5px;top:0;width:72px;height:58px;border:6px solid #d9e1e5;border-left-color:transparent;border-top-color:#8f9aa1;border-radius:62% 78% 18% 70%;transform:rotate(-20deg)}.k26handle{position:absolute;right:2px;bottom:3px;width:50px;height:19px;background:repeating-linear-gradient(90deg,#0b0c0d 0 7px,#353a3e 7px 11px);border:2px solid #050607;border-radius:9px;transform:rotate(36deg)}.k26ring{position:absolute;right:-8px;bottom:-8px;width:28px;height:28px;border:7px solid #2b3034;border-radius:50%;background:#0b0d0f}.k26name{position:absolute;left:6px;right:6px;bottom:9px;text-align:center;color:#9bd8ff;font-weight:900;font-size:13px}
#karambitV26{display:none;position:absolute;right:8vw;bottom:5vh;width:250px;height:235px;z-index:27;pointer-events:none;transform-origin:74% 80%;filter:drop-shadow(0 10px 8px #0008)}#karambitV26 .kh{position:absolute;right:18px;bottom:24px;width:92px;height:34px;border-radius:17px 8px 8px 17px;background:linear-gradient(180deg,#24282b,#0d0f11 52%,#292d30);border:2px solid #050607;transform:rotate(-34deg)}#karambitV26 .kr{position:absolute;right:3px;bottom:7px;width:43px;height:43px;border:9px solid #15191c;border-radius:50%;box-shadow:inset 0 0 0 2px #555b60,0 2px 4px #000;transform:rotate(-34deg)}#karambitV26 .kb{position:absolute;right:72px;bottom:58px;width:145px;height:120px;transform:rotate(-22deg)}#karambitV26 .kb:before{content:"";position:absolute;inset:0;background:linear-gradient(135deg,#dce4e8 0 14%,#69767e 32%,#1b2328 60%,#89969e 82%,#edf2f4);clip-path:path('M 139 100 C 104 112 65 108 36 87 C 12 70 2 43 10 14 C 32 45 58 56 87 50 C 111 45 128 29 143 6 C 150 43 149 75 139 100 Z')}
#weapon.k26 #knife{display:none!important}#weapon.k26 #butterfly{display:none!important}#weapon.k26 #karambitV26{display:block!important}
@keyframes k26draw{0%{transform:translate(120px,175px) rotate(105deg) scale(.72);opacity:0}18%{transform:translate(38px,50px) rotate(44deg) scale(.94);opacity:1}38%{transform:translate(-4px,-28px) rotate(-90deg) scale(1.04)}58%{transform:translate(8px,-48px) rotate(-235deg) scale(1.06)}78%{transform:translate(-3px,8px) rotate(-405deg) scale(1.01)}100%{transform:translate(0,0) rotate(-394deg) scale(1)}}#weapon.k26.draw26 #karambitV26{animation:k26draw .96s cubic-bezier(.18,.74,.18,1) both}
@keyframes k26inspect{0%{transform:translate(0,0) rotate(-394deg) scale(1)}15%{transform:translate(-42px,-22px) rotate(-430deg) scale(1.08)}35%{transform:translate(-104px,-90px) rotate(-620deg) scale(1.2)}55%{transform:translate(-78px,-70px) rotate(-780deg) scale(1.18)}75%{transform:translate(-34px,-34px) rotate(-930deg) scale(1.1)}100%{transform:translate(0,0) rotate(-754deg) scale(1)}}#weapon.k26.inspect26 #karambitV26{animation:k26inspect 2.05s cubic-bezier(.2,.62,.2,1) both!important}
</style>
<script>
(function(){
'use strict';
var KEY='rahl1k_inventory_v26', ACTIVE='rahl1k_active_knife_v26', selected='', lock=0, inspecting=false;
function def(){return {ct:{rifle:true,pistol:true,m9:true,butterfly:false,karambit:false},t:{rifle:true,pistol:true,m9:true,butterfly:false,karambit:false}}}
function load(){try{var d=def(),x=JSON.parse(localStorage.getItem(KEY)||localStorage.getItem('rahl1k_inventory_v25')||'{}');['ct','t'].forEach(s=>Object.assign(d[s],x[s]||{}));return d}catch(e){return def()}}
function save(x){localStorage.setItem(KEY,JSON.stringify(x))}
function act(){try{return Object.assign({ct:'m9',t:'m9'},JSON.parse(localStorage.getItem(ACTIVE)||'{}'))}catch(e){return{ct:'m9',t:'m9'}}}
function saveAct(x){localStorage.setItem(ACTIVE,JSON.stringify(x))}
function side(){try{return String(myTeam||'ct').toLowerCase()==='t'?'t':'ct'}catch(e){return'ct'}}
function kind(c){if(!c)return'';if(c.id==='bfInventoryCard')return'butterfly';if(c.id==='karambitInventoryCard')return'karambit';var w=c.dataset&&c.dataset.weapon||'';return w==='knife'?'m9':w}
function cards(){return document.querySelectorAll('#inventoryWeapons .inventoryWeaponCard,#bfInventoryCard,#karambitInventoryCard')}
function ensure(){var h=document.getElementById('inventoryWeapons');if(!h)return;var bf=document.getElementById('bfInventoryCard');if(bf){bf.classList.add('inventoryWeaponCard');bf.dataset.weapon='butterfly';bf.querySelectorAll('.bfActions,.v25checks,.v24checks').forEach(x=>x.remove());if(!bf.querySelector('.v26checks'))bf.insertAdjacentHTML('beforeend','<div class="v26checks"><div class="v26check ct">✓</div><div class="v26check t">✓</div></div>')}var k=document.getElementById('karambitInventoryCard');if(!k){k=document.createElement('div');k.id='karambitInventoryCard';k.className='inventoryWeaponCard';k.dataset.weapon='karambit';h.appendChild(k)}k.innerHTML='<div class="kType">НОЖ</div><div class="v26checks"><div class="v26check ct">✓</div><div class="v26check t">✓</div></div><div class="k26icon"><div class="k26blade"></div><div class="k26handle"></div><div class="k26ring"></div></div><div class="k26name">KARAMBIT</div>';k.style.display='flex';var w=document.getElementById('weapon');if(w&&!document.getElementById('karambitV26')){var m=document.createElement('div');m.id='karambitV26';m.innerHTML='<div class="kb"></div><div class="kh"></div><div class="kr"></div>';w.appendChild(m)}}
function applied(st,s,k){return !!st[s][k]}
function paint(){var st=load();[['bfInventoryCard','butterfly'],['karambitInventoryCard','karambit']].forEach(a=>{var c=document.getElementById(a[0]);if(!c)return;var ct=c.querySelector('.v26check.ct'),t=c.querySelector('.v26check.t');if(ct)ct.classList.toggle('on',applied(st,'ct',a[1]));if(t)t.classList.toggle('on',applied(st,'t',a[1]))})}
function render(){if(!selected)return;var st=load(),P=document.getElementById('inventoryActionPanel'),N=document.getElementById('inventorySelectedName'),C=document.getElementById('inventoryCTButton'),T=document.getElementById('inventoryTButton'),S=document.getElementById('inventoryStatus');if(P){P.classList.add('active');P.style.display='block'}if(N)N.textContent=selected==='m9'?'M9 RED DRAGON':selected==='butterfly'?'BUTTERFLY LEGACY':selected==='karambit'?'KARAMBIT':selected.toUpperCase();if(C)C.textContent=applied(st,'ct',selected)?'СНЯТЬ С CT':'ПРИМЕНИТЬ ЗА CT';if(T)T.textContent=applied(st,'t',selected)?'СНЯТЬ С T':'ПРИМЕНИТЬ ЗА T';if(S)S.textContent='Применено: '+(applied(st,'ct',selected)?'✓ CT':'— CT')+' / '+(applied(st,'t',selected)?'✓ T':'— T');paint()}
function selectCard(c,e){var k=kind(c);if(!k)return;if(e){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation&&e.stopImmediatePropagation()}selected=k;cards().forEach(x=>x.classList.remove('sel','selected'));c.classList.add('sel','selected');render();lock=Date.now()+450}
function apply(s,e){if(!selected)return;if(e){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation&&e.stopImmediatePropagation()}var st=load();st[s][selected]=!st[s][selected];save(st);if(['m9','butterfly','karambit'].includes(selected)&&st[s][selected]){var a=act();a[s]=selected;saveAct(a)}render();lock=Date.now()+450}
function currentKnife(){var s=side(),st=load(),a=act(),k=a[s];if(st[s][k])return k;return ['karambit','butterfly','m9'].find(x=>st[s][x])||'m9'}
function clearK(){var w=document.getElementById('weapon');if(w)w.classList.remove('k26','draw26','inspect26');var k=document.getElementById('karambitV26');if(k)k.style.display='none'}
function equipKnife(k){ensure();var w=document.getElementById('weapon');if(!w)return;clearK();if(k==='karambit'){try{currentWeapon='knife'}catch(e){};try{if(typeof showWeapon==='function')showWeapon('knife')}catch(e){};w.classList.add('k26','draw26');var kv=document.getElementById('karambitV26');if(kv)kv.style.display='block';setTimeout(()=>w.classList.remove('draw26'),1000);return}if(k==='butterfly'){try{if(typeof switchWeaponBaseV26==='function')return switchWeaponBaseV26('butterfly')}catch(e){};try{if(window.RAHL1K_BUTTERFLY&&window.RAHL1K_BUTTERFLY.select)return window.RAHL1K_BUTTERFLY.select()}catch(e){}}try{if(typeof switchWeaponBaseV26==='function')return switchWeaponBaseV26('knife')}catch(e){}}
if(typeof switchWeapon==='function'&&!window.switchWeaponBaseV26){window.switchWeaponBaseV26=switchWeapon;switchWeapon=function(t){if(t==='knife')return equipKnife(currentKnife());clearK();return window.switchWeaponBaseV26.apply(this,arguments)}}
if(typeof showWeapon==='function'&&!window.showWeaponBaseV26){window.showWeaponBaseV26=showWeapon;showWeapon=function(t){if(t!=='knife'&&t!=='butterfly')clearK();return window.showWeaponBaseV26.apply(this,arguments)}}
if(typeof inspectWeapon==='function'&&!window.inspectWeaponBaseV26){window.inspectWeaponBaseV26=inspectWeapon;inspectWeapon=function(){if(currentKnife()==='karambit'&&typeof currentWeapon!=='undefined'&&currentWeapon==='knife'){if(inspecting)return;inspecting=true;var w=document.getElementById('weapon');w.classList.remove('inspect26','draw26');void w.offsetWidth;w.classList.add('k26','inspect26');setTimeout(()=>{w.classList.remove('inspect26');inspecting=false},2080);return}return window.inspectWeaponBaseV26.apply(this,arguments)}}
function cardFrom(t){return t&&t.closest?t.closest('#inventoryWeapons .inventoryWeaponCard,#bfInventoryCard,#karambitInventoryCard'):null}
function cap(e){var c=cardFrom(e.target);if(c){selectCard(c,e);return}if(e.target&&e.target.id==='inventoryCTButton'){apply('ct',e);return}if(e.target&&e.target.id==='inventoryTButton'){apply('t',e);return}}
document.addEventListener('touchstart',cap,true);document.addEventListener('pointerdown',function(e){if(e.pointerType!=='touch')cap(e)},true);document.addEventListener('click',function(e){if(Date.now()<lock){var c=cardFrom(e.target);if(c||e.target&&['inventoryCTButton','inventoryTButton'].includes(e.target.id)){e.preventDefault();e.stopImmediatePropagation();return}}},true);
function tick(){ensure();paint();if(selected)render()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',tick);else tick();setTimeout(tick,200);setInterval(tick,900);
})();
</script>
'''
pos=s.rfind('</body>')
if pos<0: raise SystemExit('no body')
s=s[:pos]+addon+'\n'+s[pos:]
p.write_text(s,encoding='utf-8')
print('inventory karambit v26 patched')